### ISSUE TITLE
Webvtt dependency missing on `pip install`

### ISSUE THREAD

**Issue by jimzers** [thehetpandya/youtube_tts_data_generator#5]
Lack of `webvtt-py` package before installing is not handled in setup.py. Added the dependency.

**Comment by jimzers** [comment]
#4

**Comment by hetpandya** [comment]
Hi @jimzers, the package no longer needs `webvtt-py`. I shall remove the import from `youtube_tts_data_generator.py`  The package was needed when the captions were used in `vtt` or `srt` format. Now these caption formats are converted to `json` and by default they are saved in `json` format.

**Comment by jimzers** [comment]
Ah, I see. Thanks for the heads up @hetpandya - closed my pull request.

**Comment by hetpandya** [comment]
@jimzers, I have fixed the package. Please try using `pip install -U youtube-tts-data-generator`

**Comment by jimzers** [comment]
@hetpandya Thanks - works for me!

**Comment by hetpandya** [comment]
Glad it worked! @jimzers
